### ISSUE TITLE
error trying to install the plugin

### ISSUE THREAD

**Issue by jffs** [ezartech/ezar-compass#1]
i cant download the SDK from the page

**Comment by ezartech** [comment]
My bad. I'm updating this project today to support the new ezar 0.2.0 plugins. I'll close this issue once I have when I complete the update later today. Also, you will need to manually download the ezar plugins as part of the ezar startup kit and add them to the project: http://www.ezartech.com/download/

**Comment by ezartech** [comment]
jfffs, I updated this project today. Please see the README  doc for instructions on adding plugins to the project. You'll need to download and install the latest version of ezAR Startup Kit, see http://www.ezartech.com/download/
